"""initial schema: users presets trees and workspace

Revision ID: e3b0252d91eb
Revises: 
Create Date: 2026-01-20 05:13:53.104675

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = 'e3b0252d91eb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trees',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('census_tree_id', sa.String(length=64), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('borough', sa.String(length=50), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('location', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('species', sa.String(length=100), nullable=True),
    sa.Column('health', sa.String(length=10), nullable=True),
    sa.Column('health_score', sa.Integer(), nullable=True),
    sa.Column('dbh', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("health IN ('Good', 'Fair', 'Poor') OR health IS NULL", name='ck_trees_health'),
    sa.CheckConstraint('health_score IN (0, 1, 2) OR health_score IS NULL', name='ck_trees_health_score'),
    sa.CheckConstraint('latitude BETWEEN -90 AND 90', name='ck_trees_latitude'),
    sa.CheckConstraint('longitude BETWEEN -180 AND 180', name='ck_trees_longitude'),
    sa.CheckConstraint('year IN (1995, 2005, 2015)', name='ck_trees_year'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('year', 'census_tree_id', name='uq_trees_year_census_tree_id')
    )
    # Manually create spatial index (mysql_using parameter doesn't work correctly)
    op.execute('CREATE SPATIAL INDEX ix_trees_location ON trees (location)')
    op.create_index('ix_trees_year_borough', 'trees', ['year', 'borough'], unique=False)
    op.create_index('ix_trees_year_health', 'trees', ['year', 'health'], unique=False)
    op.create_index('ix_trees_year_species', 'trees', ['year', 'species'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('datasets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('raw_path', sa.String(length=500), nullable=False),
    sa.Column('parquet_path', sa.String(length=500), nullable=True),
    sa.Column('row_count', sa.Integer(), nullable=True),
    sa.Column('column_count', sa.Integer(), nullable=True),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('error_message', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('uploaded', 'profiling', 'ready', 'failed')", name='ck_datasets_status'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_datasets_user_id'), 'datasets', ['user_id'], unique=False)
    op.create_table('presets',
    sa.Column('preset_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('study', sa.String(length=2), nullable=False),
    sa.Column('view', sa.String(length=5), nullable=False),
    sa.Column('filters', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("study IN ('S1','S2')", name='ck_presets_study'),
    sa.CheckConstraint("view IN ('table','map')", name='ck_presets_view'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('preset_id'),
    sa.UniqueConstraint('user_id', 'name', name='uq_presets_user_id_name')
    )
    op.create_table('charts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('dataset_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('chart_type', sa.String(length=50), nullable=False),
    sa.Column('spec_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("chart_type IN ('bar', 'line', 'scatter', 'hist', 'box')", name='ck_charts_chart_type'),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_charts_dataset_id'), 'charts', ['dataset_id'], unique=False)
    op.create_index(op.f('ix_charts_user_id'), 'charts', ['user_id'], unique=False)
    op.create_table('dataset_columns',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('dataset_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('inferred_type', sa.String(length=50), nullable=False),
    sa.Column('nullable', sa.Boolean(), nullable=False),
    sa.Column('sample_values', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dataset_id', 'name', name='uq_dataset_columns_dataset_id_name')
    )
    op.create_index(op.f('ix_dataset_columns_dataset_id'), 'dataset_columns', ['dataset_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dataset_columns_dataset_id'), table_name='dataset_columns')
    op.drop_table('dataset_columns')
    op.drop_index(op.f('ix_charts_user_id'), table_name='charts')
    op.drop_index(op.f('ix_charts_dataset_id'), table_name='charts')
    op.drop_table('charts')
    op.drop_table('presets')
    op.drop_index(op.f('ix_datasets_user_id'), table_name='datasets')
    op.drop_table('datasets')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index('ix_trees_year_species', table_name='trees')
    op.drop_index('ix_trees_year_health', table_name='trees')
    op.drop_index('ix_trees_year_borough', table_name='trees')
    # Manually drop spatial index
    op.execute('DROP INDEX ix_trees_location ON trees')
    op.drop_table('trees')
    # ### end Alembic commands ###